  
[build]
  base = "frontend"
  command = "npm run build"
  publish = "public"
[[plugins]]
package = "netlify-plugin-gatsby-cache"
[[plugins]]
package = "netlify-plugin-cypress"
[[plugins]]
package = "netlify-plugin-a11y"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]
  
  # required config
  checkPaths = ['/public']

  # # optional config
  # ignoreDirectories = ['/admin']  # explicitly ignore these directories

  resultMode = "warn" # is "error" by default